### PR TITLE
edited enum names due to naming conflicts

### PR DESCRIPTION
**Pull request by quotschmacher**
i had some trouble cause in some windows files there was "ERROR"-define which caused naming conflicts with your library

### CODE REVIEW

**Comment by lahwaacz** [comment]
You should consider using [scoped enumerations](https://en.cppreference.com/w/cpp/language/enum#Scoped_enumerations) (`enum class`) instead.

**Comment by quotschmacher** [comment]
how should this help? something in my project (i would guess it is wxwidgets) is includeing a file called "wingdi.h" where i can find a define `#define ERROR               0` and in your enum there also is error.

**Comment by lahwaacz** [comment]
If you use scoped enumerations, you always need to use scoped access to your enum entries, i.e. `LineType::ERROR`.

**Comment by quotschmacher** [comment]
yes, in the usage i see the advantage, but the error happens while the declaration. there "error" is set as 4 oder 5 i think, but it is replaced by the define s 0 = 4? doesn't work.

**Comment by lahwaacz** [comment]
Oh. So you need to rename the entries after all.

**Comment by quotschmacher** [comment]
That's what my pull request does. Maybe not the luckiest choice of prefix, but it is way more unique and probably not conflicting with other defines.

**Comment by Lek-sys** [comment]
Yes, thanks for noticing.

**Pull request merged**
